spring.application.name=intro
spring.h2.console.enabled = true
spring.datasource.url = jdbc:h2:file:/Users/GAUTHAMI/OneDrive/Desktop/sql
spring.datasource.username = bhargav
spring.datasource.password = bhargav123
spring.jpa.hibernate.ddl-auto=update
