/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as FacultyIndexRouteImport } from './routes/faculty.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentDepartmentRouteImport } from './routes/student.department'
import { Route as StudentCoursesRouteImport } from './routes/student.courses'
import { Route as StudentChangePasswordRouteImport } from './routes/student.change-password'
import { Route as FacultyStudentsByCourseRouteImport } from './routes/faculty.students-by-course'
import { Route as FacultyProfileRouteImport } from './routes/faculty.profile'
import { Route as FacultyCoursesRouteImport } from './routes/faculty.courses'
import { Route as FacultyChangePasswordRouteImport } from './routes/faculty.change-password'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminFacultiesRouteImport } from './routes/admin.faculties'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminChangePasswordRouteImport } from './routes/admin.change-password'
import { Route as StudentFacultiesIdRouteImport } from './routes/student/faculties/$id'
import { Route as AdminStudentsIdRouteImport } from './routes/admin/students/$id'
import { Route as AdminFacultiesIdRouteImport } from './routes/admin/faculties/$id'
import { Route as AdminDepartmentsIdRouteImport } from './routes/admin/departments/$id'
import { Route as AdminCoursesIdRouteImport } from './routes/admin/courses/$id'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const FacultyIndexRoute = FacultyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FacultyRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDepartmentRoute = StudentDepartmentRouteImport.update({
  id: '/department',
  path: '/department',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const StudentChangePasswordRoute = StudentChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => StudentRoute,
} as any)
const FacultyStudentsByCourseRoute = FacultyStudentsByCourseRouteImport.update({
  id: '/students-by-course',
  path: '/students-by-course',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyProfileRoute = FacultyProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyCoursesRoute = FacultyCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyChangePasswordRoute = FacultyChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => FacultyRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacultiesRoute = AdminFacultiesRouteImport.update({
  id: '/faculties',
  path: '/faculties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChangePasswordRoute = AdminChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AdminRoute,
} as any)
const StudentFacultiesIdRoute = StudentFacultiesIdRouteImport.update({
  id: '/faculties/$id',
  path: '/faculties/$id',
  getParentRoute: () => StudentRoute,
} as any)
const AdminStudentsIdRoute = AdminStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminStudentsRoute,
} as any)
const AdminFacultiesIdRoute = AdminFacultiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminFacultiesRoute,
} as any)
const AdminDepartmentsIdRoute = AdminDepartmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminDepartmentsRoute,
} as any)
const AdminCoursesIdRoute = AdminCoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/faculty': typeof FacultyRouteWithChildren
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/departments': typeof AdminDepartmentsRouteWithChildren
  '/admin/faculties': typeof AdminFacultiesRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/students': typeof AdminStudentsRouteWithChildren
  '/faculty/change-password': typeof FacultyChangePasswordRoute
  '/faculty/courses': typeof FacultyCoursesRoute
  '/faculty/profile': typeof FacultyProfileRoute
  '/faculty/students-by-course': typeof FacultyStudentsByCourseRoute
  '/student/change-password': typeof StudentChangePasswordRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/department': typeof StudentDepartmentRoute
  '/student/profile': typeof StudentProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/admin/departments/$id': typeof AdminDepartmentsIdRoute
  '/admin/faculties/$id': typeof AdminFacultiesIdRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
  '/student/faculties/$id': typeof StudentFacultiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/departments': typeof AdminDepartmentsRouteWithChildren
  '/admin/faculties': typeof AdminFacultiesRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/students': typeof AdminStudentsRouteWithChildren
  '/faculty/change-password': typeof FacultyChangePasswordRoute
  '/faculty/courses': typeof FacultyCoursesRoute
  '/faculty/profile': typeof FacultyProfileRoute
  '/faculty/students-by-course': typeof FacultyStudentsByCourseRoute
  '/student/change-password': typeof StudentChangePasswordRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/department': typeof StudentDepartmentRoute
  '/student/profile': typeof StudentProfileRoute
  '/admin': typeof AdminIndexRoute
  '/faculty': typeof FacultyIndexRoute
  '/student': typeof StudentIndexRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/admin/departments/$id': typeof AdminDepartmentsIdRoute
  '/admin/faculties/$id': typeof AdminFacultiesIdRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
  '/student/faculties/$id': typeof StudentFacultiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/faculty': typeof FacultyRouteWithChildren
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/departments': typeof AdminDepartmentsRouteWithChildren
  '/admin/faculties': typeof AdminFacultiesRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/students': typeof AdminStudentsRouteWithChildren
  '/faculty/change-password': typeof FacultyChangePasswordRoute
  '/faculty/courses': typeof FacultyCoursesRoute
  '/faculty/profile': typeof FacultyProfileRoute
  '/faculty/students-by-course': typeof FacultyStudentsByCourseRoute
  '/student/change-password': typeof StudentChangePasswordRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/department': typeof StudentDepartmentRoute
  '/student/profile': typeof StudentProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/admin/departments/$id': typeof AdminDepartmentsIdRoute
  '/admin/faculties/$id': typeof AdminFacultiesIdRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
  '/student/faculties/$id': typeof StudentFacultiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/faculty'
    | '/login'
    | '/student'
    | '/admin/change-password'
    | '/admin/courses'
    | '/admin/departments'
    | '/admin/faculties'
    | '/admin/profile'
    | '/admin/students'
    | '/faculty/change-password'
    | '/faculty/courses'
    | '/faculty/profile'
    | '/faculty/students-by-course'
    | '/student/change-password'
    | '/student/courses'
    | '/student/department'
    | '/student/profile'
    | '/admin/'
    | '/faculty/'
    | '/student/'
    | '/admin/courses/$id'
    | '/admin/departments/$id'
    | '/admin/faculties/$id'
    | '/admin/students/$id'
    | '/student/faculties/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/change-password'
    | '/admin/courses'
    | '/admin/departments'
    | '/admin/faculties'
    | '/admin/profile'
    | '/admin/students'
    | '/faculty/change-password'
    | '/faculty/courses'
    | '/faculty/profile'
    | '/faculty/students-by-course'
    | '/student/change-password'
    | '/student/courses'
    | '/student/department'
    | '/student/profile'
    | '/admin'
    | '/faculty'
    | '/student'
    | '/admin/courses/$id'
    | '/admin/departments/$id'
    | '/admin/faculties/$id'
    | '/admin/students/$id'
    | '/student/faculties/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/faculty'
    | '/login'
    | '/student'
    | '/admin/change-password'
    | '/admin/courses'
    | '/admin/departments'
    | '/admin/faculties'
    | '/admin/profile'
    | '/admin/students'
    | '/faculty/change-password'
    | '/faculty/courses'
    | '/faculty/profile'
    | '/faculty/students-by-course'
    | '/student/change-password'
    | '/student/courses'
    | '/student/department'
    | '/student/profile'
    | '/admin/'
    | '/faculty/'
    | '/student/'
    | '/admin/courses/$id'
    | '/admin/departments/$id'
    | '/admin/faculties/$id'
    | '/admin/students/$id'
    | '/student/faculties/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FacultyRoute: typeof FacultyRouteWithChildren
  LoginRoute: typeof LoginRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/faculty/': {
      id: '/faculty/'
      path: '/'
      fullPath: '/faculty/'
      preLoaderRoute: typeof FacultyIndexRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/department': {
      id: '/student/department'
      path: '/department'
      fullPath: '/student/department'
      preLoaderRoute: typeof StudentDepartmentRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/change-password': {
      id: '/student/change-password'
      path: '/change-password'
      fullPath: '/student/change-password'
      preLoaderRoute: typeof StudentChangePasswordRouteImport
      parentRoute: typeof StudentRoute
    }
    '/faculty/students-by-course': {
      id: '/faculty/students-by-course'
      path: '/students-by-course'
      fullPath: '/faculty/students-by-course'
      preLoaderRoute: typeof FacultyStudentsByCourseRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/profile': {
      id: '/faculty/profile'
      path: '/profile'
      fullPath: '/faculty/profile'
      preLoaderRoute: typeof FacultyProfileRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/courses': {
      id: '/faculty/courses'
      path: '/courses'
      fullPath: '/faculty/courses'
      preLoaderRoute: typeof FacultyCoursesRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/change-password': {
      id: '/faculty/change-password'
      path: '/change-password'
      fullPath: '/faculty/change-password'
      preLoaderRoute: typeof FacultyChangePasswordRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faculties': {
      id: '/admin/faculties'
      path: '/faculties'
      fullPath: '/admin/faculties'
      preLoaderRoute: typeof AdminFacultiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/change-password': {
      id: '/admin/change-password'
      path: '/change-password'
      fullPath: '/admin/change-password'
      preLoaderRoute: typeof AdminChangePasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/faculties/$id': {
      id: '/student/faculties/$id'
      path: '/faculties/$id'
      fullPath: '/student/faculties/$id'
      preLoaderRoute: typeof StudentFacultiesIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/students/$id': {
      id: '/admin/students/$id'
      path: '/$id'
      fullPath: '/admin/students/$id'
      preLoaderRoute: typeof AdminStudentsIdRouteImport
      parentRoute: typeof AdminStudentsRoute
    }
    '/admin/faculties/$id': {
      id: '/admin/faculties/$id'
      path: '/$id'
      fullPath: '/admin/faculties/$id'
      preLoaderRoute: typeof AdminFacultiesIdRouteImport
      parentRoute: typeof AdminFacultiesRoute
    }
    '/admin/departments/$id': {
      id: '/admin/departments/$id'
      path: '/$id'
      fullPath: '/admin/departments/$id'
      preLoaderRoute: typeof AdminDepartmentsIdRouteImport
      parentRoute: typeof AdminDepartmentsRoute
    }
    '/admin/courses/$id': {
      id: '/admin/courses/$id'
      path: '/$id'
      fullPath: '/admin/courses/$id'
      preLoaderRoute: typeof AdminCoursesIdRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
  }
}

interface AdminCoursesRouteChildren {
  AdminCoursesIdRoute: typeof AdminCoursesIdRoute
}

const AdminCoursesRouteChildren: AdminCoursesRouteChildren = {
  AdminCoursesIdRoute: AdminCoursesIdRoute,
}

const AdminCoursesRouteWithChildren = AdminCoursesRoute._addFileChildren(
  AdminCoursesRouteChildren,
)

interface AdminDepartmentsRouteChildren {
  AdminDepartmentsIdRoute: typeof AdminDepartmentsIdRoute
}

const AdminDepartmentsRouteChildren: AdminDepartmentsRouteChildren = {
  AdminDepartmentsIdRoute: AdminDepartmentsIdRoute,
}

const AdminDepartmentsRouteWithChildren =
  AdminDepartmentsRoute._addFileChildren(AdminDepartmentsRouteChildren)

interface AdminFacultiesRouteChildren {
  AdminFacultiesIdRoute: typeof AdminFacultiesIdRoute
}

const AdminFacultiesRouteChildren: AdminFacultiesRouteChildren = {
  AdminFacultiesIdRoute: AdminFacultiesIdRoute,
}

const AdminFacultiesRouteWithChildren = AdminFacultiesRoute._addFileChildren(
  AdminFacultiesRouteChildren,
)

interface AdminStudentsRouteChildren {
  AdminStudentsIdRoute: typeof AdminStudentsIdRoute
}

const AdminStudentsRouteChildren: AdminStudentsRouteChildren = {
  AdminStudentsIdRoute: AdminStudentsIdRoute,
}

const AdminStudentsRouteWithChildren = AdminStudentsRoute._addFileChildren(
  AdminStudentsRouteChildren,
)

interface AdminRouteChildren {
  AdminChangePasswordRoute: typeof AdminChangePasswordRoute
  AdminCoursesRoute: typeof AdminCoursesRouteWithChildren
  AdminDepartmentsRoute: typeof AdminDepartmentsRouteWithChildren
  AdminFacultiesRoute: typeof AdminFacultiesRouteWithChildren
  AdminProfileRoute: typeof AdminProfileRoute
  AdminStudentsRoute: typeof AdminStudentsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChangePasswordRoute: AdminChangePasswordRoute,
  AdminCoursesRoute: AdminCoursesRouteWithChildren,
  AdminDepartmentsRoute: AdminDepartmentsRouteWithChildren,
  AdminFacultiesRoute: AdminFacultiesRouteWithChildren,
  AdminProfileRoute: AdminProfileRoute,
  AdminStudentsRoute: AdminStudentsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FacultyRouteChildren {
  FacultyChangePasswordRoute: typeof FacultyChangePasswordRoute
  FacultyCoursesRoute: typeof FacultyCoursesRoute
  FacultyProfileRoute: typeof FacultyProfileRoute
  FacultyStudentsByCourseRoute: typeof FacultyStudentsByCourseRoute
  FacultyIndexRoute: typeof FacultyIndexRoute
}

const FacultyRouteChildren: FacultyRouteChildren = {
  FacultyChangePasswordRoute: FacultyChangePasswordRoute,
  FacultyCoursesRoute: FacultyCoursesRoute,
  FacultyProfileRoute: FacultyProfileRoute,
  FacultyStudentsByCourseRoute: FacultyStudentsByCourseRoute,
  FacultyIndexRoute: FacultyIndexRoute,
}

const FacultyRouteWithChildren =
  FacultyRoute._addFileChildren(FacultyRouteChildren)

interface StudentRouteChildren {
  StudentChangePasswordRoute: typeof StudentChangePasswordRoute
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentDepartmentRoute: typeof StudentDepartmentRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentFacultiesIdRoute: typeof StudentFacultiesIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentChangePasswordRoute: StudentChangePasswordRoute,
  StudentCoursesRoute: StudentCoursesRoute,
  StudentDepartmentRoute: StudentDepartmentRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentFacultiesIdRoute: StudentFacultiesIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FacultyRoute: FacultyRouteWithChildren,
  LoginRoute: LoginRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
